import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import { useContext } from 'react';
import { SpotifyContext } from '../context/SpotifyContext';
import { useGetUsersQuery } from '../graphql/__generated__';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  // const { data } = useGetUsersQuery();
  const { player, api, state } = useContext(SpotifyContext);
  console.log(state);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <button
          onClick={async () => {
            await api?.playAlbumOrPlaylist(
              'spotify:playlist:0zjma4HRqmvGwiAFfR5hnp'
            );
          }}
        >
          play
        </button>
        <button
          onClick={async () => {
            player?.pause();
          }}
        >
          pause
        </button>
        <button
          onClick={async () => {
            player?.resume();
          }}
        >
          resume
        </button>
      </main>
    </div>
  );
};

export default Home;
